package View;

import View.Listeners.LoginListener;
import com.toedter.calendar.JCalendar;
import com.toedter.calendar.JDateChooser;

import javax.swing.*;
import java.awt.*;

public class RegisterPanel extends JPanel {

    public RegisterPanel() {
        this.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(3,10,3,10);
        JLabel textNome = new JLabel("Nome");
        JLabel textCognome = new JLabel("Cognome");
        JLabel textEmail = new JLabel("Email");
        JLabel textUsername = new JLabel("Username");
        JLabel textPassword = new JLabel("Password");
        JLabel textTelefono = new JLabel("Telefono");
        JLabel textDataNascita = new JLabel("Data di nascita");
        JLabel textNazione  = new JLabel("Nazione");
        JLabel textCitta = new JLabel("Citta");
        JLabel textCap = new JLabel("Cap");
        JLabel textVia = new JLabel("Via");
        JLabel textCivico = new JLabel("Civico");
        JTextField nome = new JTextField(20);
        JTextField cognome = new JTextField(20);
        JTextField email = new JTextField(20);
        JTextField telefono = new JTextField(20);
        JDateChooser dataNascita = new JDateChooser();
        JTextField nazione = new JTextField(20);
        JTextField citta = new JTextField(20);
        JTextField cap = new JTextField(20);
        JTextField via = new JTextField(20);
        JTextField civico = new JTextField(20);

        JTextField username = new JTextField(20);
        JPasswordField password = new JPasswordField(20);
        JButton register = new JButton("Registrati");
        register.setFocusPainted(false);
        register.setActionCommand(LoginListener.REGISTER_BTN);
        LoginListener loginListener = new LoginListener(username, password);
        register.addActionListener(loginListener);
        JDateChooser compleanno = new JDateChooser();
        gbc.gridx=0;
        gbc.gridy=0;
        this.add(textNome,gbc);
        gbc.gridx=1;
        this.add(new JLabel(""));
        gbc.gridx=2;
        this.add(textCognome,gbc);
        gbc.gridy=1;
        gbc.gridx=0;
        this.add(nome,gbc);
        gbc.gridx=2;
        this.add(cognome,gbc);
        gbc.gridy=2;
        gbc.gridx=0;
        gbc.gridwidth=3;
        this.add(textEmail,gbc);
        gbc.gridy=3;
        this.add(email,gbc);
        gbc.gridwidth=1;
        gbc.gridy=4;
        this.add(textTelefono,gbc);
        gbc.gridx=2;
        this.add(textDataNascita,gbc);
        gbc.gridy=5;
        gbc.gridx=0;
        this.add(telefono,gbc);
        gbc.gridx=2;
        this.add(dataNascita,gbc);
        gbc.gridx=0;
        gbc.gridy=6;
        this.add(textNazione,gbc);
        gbc.gridx=1;
        this.add(textCitta,gbc);
        gbc.gridx=2;
        this.add(textCap,gbc);
        gbc.gridx=0;
        gbc.gridy=7;
        this.add(nazione,gbc);
        gbc.gridx=1;
        this.add(citta,gbc);
        gbc.gridx=2;
        this.add(cap,gbc);
        gbc.gridx=0;
        gbc.gridy=8;
        this.add(textVia,gbc);
        gbc.gridx=2;
        this.add(textCivico,gbc);
        gbc.gridx=0;
        gbc.gridy=9;
        gbc.gridwidth=2;
        this.add(via,gbc);
        gbc.gridx=2;
        gbc.gridwidth=1;
        this.add(civico,gbc);
        gbc.gridwidth=3;
        gbc.gridx=0;
        gbc.gridy=10;
        this.add(textUsername,gbc);
        gbc.gridy=11;
        this.add(username,gbc);
        gbc.gridy=12;
        this.add(textPassword,gbc);
        gbc.gridy=13;
        this.add(password,gbc);
        gbc.gridy=14;
        this.add(register,gbc);
    }
}
